[package]
name = "light-emitting-diode"
version = "0.1.0"
authors = ["qcteq <qcteqcr-environment-builder@qcteq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
rust_gpiozero= "0.2.1"
